# Default values for ladeit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: ladeit/ladeit
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: ladeit
  type: ClusterIP
  externalPort: 8000
  internalPort: 8000
ingress:
  enabled: true
  hosts:
    - ladeit-example.local
resources:
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 500m
    memory: 1Gi
volume:
  enabled: false
  mountPath: /root/.ladeit
  name: ladeit
persistentVolumeClaim:
  enabled: false
  claimName: ladeit
